title: "Mein Portfolio"
description: "Portfolio – Projekte, Reisen & mehr"
baseurl: ""
url: ""

# Wichtig für GitHub Pages
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
nav:
  - name: "Home"
    url: "/"
  - name: "Projekte"
    url: "/projekte/"
  - name: "Reisen"
    url: "/reisen/"

# Collections
collections:
  projects:
    output: true
    permalink: /projekte/:name/
  travels:
    output: true
    permalink: /reisen/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "travels"
    values:
      layout: "travel"

# Markdown
markdown: kramdown
highlighter: rouge

# Ausschließen
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
